<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class C_jabatan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_jabatan');
        $this->load->library('form_validation');
	      $this->load->library('datatables');
    }

    public function index()
    {
        if(($this->session->userdata('ses_username') == null) or ($this->session->userdata('ses_pass') == null))
        {
          header('Location: '.base_url().'login');
        } else {
          $this->load->view('admin/page/c_jabatan/jabatan.html');
        }
    }

    public function json() {
        header('Content-Type: application/json');
        echo $this->M_jabatan->json();
    }

    public function create()
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('c_jabatan/create_action'),
      	    'id_jabatan' => set_value('id_jabatan'),
      	    'kode_jabatan' => set_value('kode_jabatan'),
      	    'nama_jabatan' => set_value('nama_jabatan'),
      	    'ket_jabatan' => set_value('ket_jabatan'),
      	);
        $this->load->view('admin/page/c_jabatan/input_jabatan.html', $data);
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $tgl = date('Y-m-d H:i:s');
            $data = array(
          		'kode_jabatan' => $this->input->post('kode_jabatan',TRUE),
          		'nama_jabatan' => $this->input->post('nama_jabatan',TRUE),
          		'ket_jabatan' => $this->input->post('ket_jabatan',TRUE),
          		'tgl_insert' => $tgl,
          		'user' => $this->session->userdata('ses_id_akun'),
      	    );

            $this->M_jabatan->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('jabatan'));
        }
    }

    public function update($id)
    {
        $row = $this->M_jabatan->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('c_jabatan/update_action'),
            		'id_jabatan' => set_value('id_jabatan', $row->id_jabatan),
            		'kode_jabatan' => set_value('kode_jabatan', $row->kode_jabatan),
            		'nama_jabatan' => set_value('nama_jabatan', $row->nama_jabatan),
            		'ket_jabatan' => set_value('ket_jabatan', $row->ket_jabatan),
      	    );
            $this->load->view('admin/page/c_jabatan/input_jabatan.html', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jabatan'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_jabatan', TRUE));
        } else {
            $tgl = date('Y-m-d H:i:s');

            $data = array(
          		'kode_jabatan' => $this->input->post('kode_jabatan',TRUE),
          		'nama_jabatan' => $this->input->post('nama_jabatan',TRUE),
          		'ket_jabatan' => $this->input->post('ket_jabatan',TRUE),
          		'tgl_update' => $tgl,
          		'user' => $this->session->userdata('ses_id_akun'),
      	    );

            $this->M_jabatan->update($this->input->post('id_jabatan', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('jabatan'));
        }
    }

    public function delete($id)
    {
        $row = $this->M_jabatan->get_by_id($id);

        if ($row) {
            $this->M_jabatan->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('jabatan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jabatan'));
        }
    }

    public function _rules()
    {
      	$this->form_validation->set_rules('kode_jabatan', 'kode jabatan', 'trim|required|is_unique[tb_jabatan.kode_jabatan]');
      	$this->form_validation->set_rules('nama_jabatan', 'nama jabatan', 'trim|required');
      	$this->form_validation->set_rules('ket_jabatan', 'ket jabatan', 'trim|required');

      	$this->form_validation->set_rules('id_jabatan', 'id_jabatan', 'trim');
      	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file C_jabatan.php */
/* Location: ./application/controllers/C_jabatan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-06-29 12:46:48 */
/* http://harviacode.com */
