<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class C_kat_bayaran extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_kat_bayaran');
        $this->load->library('form_validation');
	$this->load->library('datatables');
    }

    public function index()
    {
        if(($this->session->userdata('ses_username') == null) or ($this->session->userdata('ses_pass') == null))
        {
          header('Location: '.base_url().'login');
        } else {
          $this->load->view('admin/page/c_kat_bayaran/kat_bayaran.html');
        }
    }

    public function json() {
        header('Content-Type: application/json');
        echo $this->M_kat_bayaran->json();
    }

    public function create()
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('c_kat_bayaran/create_action'),
      	    'id_kat_bayaran' => set_value('id_kat_bayaran'),
      	    'kode_kat_bayaran' => set_value('kode_kat_bayaran'),
      	    'nama_kat_bayaran' => set_value('nama_kat_bayaran'),
      	    'keterangan' => set_value('keterangan'),
      	);
        $this->load->view('admin/page/c_kat_bayaran/input_kat_bayaran.html', $data);
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $tgl = date('Y-m-d H:i:s');
            $data = array(
          		'kode_kat_bayaran' => $this->input->post('kode_kat_bayaran',TRUE),
          		'nama_kat_bayaran' => $this->input->post('nama_kat_bayaran',TRUE),
          		'keterangan' => $this->input->post('keterangan',TRUE),
          		'tgl_ins' => $tgl,
          		'user_updt' => $this->session->userdata('ses_id_akun'),
          	);

            $this->M_kat_bayaran->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('kat-bayaran'));
        }
    }

    public function update($id)
    {
        $row = $this->M_kat_bayaran->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('c_kat_bayaran/update_action'),
            		'id_kat_bayaran' => set_value('id_kat_bayaran', $row->id_kat_bayaran),
            		'kode_kat_bayaran' => set_value('kode_kat_bayaran', $row->kode_kat_bayaran),
            		'nama_kat_bayaran' => set_value('nama_kat_bayaran', $row->nama_kat_bayaran),
            		'keterangan' => set_value('keterangan', $row->keterangan),
            );
            $this->load->view('admin/page/c_kat_bayaran/input_kat_bayaran.html', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kat-bayaran'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_kat_bayaran', TRUE));
        } else {
            $tgl = date('Y-m-d H:i:s');
            $data = array(
          		'kode_kat_bayaran' => $this->input->post('kode_kat_bayaran',TRUE),
          		'nama_kat_bayaran' => $this->input->post('nama_kat_bayaran',TRUE),
          		'keterangan' => $this->input->post('keterangan',TRUE),
          		'tgl_updt' => $tgl,
          		'user_updt' => $this->session->userdata('ses_id_akun'),
          	);

            $this->M_kat_bayaran->update($this->input->post('id_kat_bayaran', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('kat-bayaran'));
        }
    }

    public function delete($id)
    {
        $row = $this->M_kat_bayaran->get_by_id($id);

        if ($row) {
            $this->M_kat_bayaran->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('kat-bayaran'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kat-bayaran'));
        }
    }

    public function _rules()
    {
      	$this->form_validation->set_rules('kode_kat_bayaran', 'kode kat bayaran', 'trim|required');
      	$this->form_validation->set_rules('nama_kat_bayaran', 'nama kat bayaran', 'trim|required');
      	$this->form_validation->set_rules('keterangan', 'keterangan', 'trim|required');

      	$this->form_validation->set_rules('id_kat_bayaran', 'id_kat_bayaran', 'trim');
      	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file C_kat_bayaran.php */
/* Location: ./application/controllers/C_kat_bayaran.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-07-15 17:49:22 */
/* http://harviacode.com */
