<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class C_semester extends CI_Controller
{
    function __construct()
    {
         parent::__construct();
         $this->load->model('M_semester');
         $this->load->library('form_validation');
	       $this->load->library('datatables');
    }

    public function index()
    {
      if(($this->session->userdata('ses_username') == null) or ($this->session->userdata('ses_pass') == null))
      {
        header('Location: '.base_url().'login');
      } else {
        $this->load->view('admin/page/c_semester/semester.html');
      }
    }

    public function json() {
        header('Content-Type: application/json');
        echo $this->M_semester->json();
    }

    public function create()
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('c_semester/create_action'),
      	    'id_semester' => set_value('id_semester'),
      	    'kode_semester' => set_value('kode_semester'),
      	    'nama_semester' => set_value('nama_semester'),
      	    'set_aktif' => set_value('set_aktif'),
      	);
        $this->load->view('admin/page/c_semester/input_semester.html', $data);
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $tgl = date('Y-m-d H:i:s');

            $data = array(
          		'kode_semester' => $this->input->post('kode_semester',TRUE),
          		'nama_semester' => $this->input->post('nama_semester',TRUE),
          		'tgl_ins' => $tgl,
          		'user_updt' => $this->session->userdata('ses_id_akun'),
          	);

            $this->M_semester->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('semester'));
        }
    }

    public function update($id)
    {
        $row = $this->M_semester->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('c_semester/update_action'),
            		'id_semester' => set_value('id_semester', $row->id_semester),
            		'kode_semester' => set_value('kode_semester', $row->kode_semester),
            		'nama_semester' => set_value('nama_semester', $row->nama_semester),
            );
            $this->load->view('admin/page/c_semester/input_semester.html', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('semester'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_semester', TRUE));
        } else {
            $tgl = date('Y-m-d H:i:s');
            $data = array(
          		'kode_semester' => $this->input->post('kode_semester',TRUE),
          		'nama_semester' => $this->input->post('nama_semester',TRUE),
          		'set_aktif' => $this->input->post('set_aktif',TRUE),
          		'tgl_updt' => $tgl,
          		'user_updt' => $this->session->userdata('ses_id_akun'),
          	);

            $this->M_semester->update($this->input->post('id_semester', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('c_semester'));
        }
    }

    public function delete($id)
    {
        $row = $this->M_semester->get_by_id($id);

        if ($row) {
            $this->M_semester->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('semester'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('semester'));
        }
    }

    public function _rules()
    {
      	$this->form_validation->set_rules('kode_semester', 'kode semester', 'trim|required');
      	$this->form_validation->set_rules('nama_semester', 'nama semester', 'trim|required');

      	$this->form_validation->set_rules('id_semester', 'id_semester', 'trim');
      	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file C_semester.php */
/* Location: ./application/controllers/C_semester.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-25 07:48:58 */
/* http://harviacode.com */
