<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_bayaran extends CI_Model
{

    public $table = 'tb_bayaran';
    public $id = 'id_bayaran';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_bayaran,kode_bayaran,nama_kat_bayaran,nama_bayaran,nominal');
        $this->datatables->from('tb_bayaran');
        //add this line for join
        $this->datatables->join('tb_kat_bayaran', 'tb_bayaran.id_kat_bayaran = tb_kat_bayaran.id_kat_bayaran');
        $this->datatables->add_column('action', anchor(site_url('c_bayaran/update/$1'),'Update')." | ".anchor(site_url('c_bayaran/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_bayaran');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        //$this->db->order_by($this->id, $this->order);
        //return $this->db->get($this->table)->result();

        $this->db->select('*');
        $this->db->from($this->table);
        $this->db->join('tb_kat_bayaran', 'tb_bayaran.id_kat_bayaran = tb_kat_bayaran.id_kat_bayaran');
        $this->db->order_by('tb_bayaran.id_kat_bayaran', $this->order);
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        // $this->db->where($this->id, $id);
        // return $this->db->get($this->table)->row();
        $this->db->select('*');
        $this->db->from($this->table);
        $this->db->join('tb_kat_bayaran', 'tb_bayaran.id_kat_bayaran = tb_kat_bayaran.id_kat_bayaran');
        $this->db->where($this->id, $id);
        return $this->db->get()->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_bayaran', $q);
      	$this->db->or_like('kode_bayaran', $q);
      	$this->db->or_like('nama_bayaran', $q);
      	$this->db->or_like('nominal', $q);
      	$this->db->or_like('keterangan', $q);
      	$this->db->or_like('tgl_ins', $q);
      	$this->db->or_like('tgl_updt', $q);
      	$this->db->or_like('user_updt', $q);
      	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_bayaran', $q);
	$this->db->or_like('kode_bayaran', $q);
	$this->db->or_like('nama_bayaran', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('tgl_ins', $q);
	$this->db->or_like('tgl_updt', $q);
	$this->db->or_like('user_updt', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_bayaran.php */
/* Location: ./application/models/M_bayaran.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-07-09 02:21:46 */
/* http://harviacode.com */
