<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_bank extends CI_Model
{

    public $table = 'tb_bank';
    public $id = 'id_bank';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_bank,norek,nama_bank,atas_nama,cabang,tgl_pembuatan,ket_bank,tgl_ins,tgl_updt,user_updt');
        $this->datatables->from('tb_bank');
        //add this line for join
        //$this->datatables->join('table2', 'tb_bank.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('c_bank/read/$1'),'Read')." | ".anchor(site_url('c_bank/update/$1'),'Update')." | ".anchor(site_url('c_bank/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_bank');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_bank', $q);
	$this->db->or_like('norek', $q);
	$this->db->or_like('nama_bank', $q);
	$this->db->or_like('atas_nama', $q);
	$this->db->or_like('cabang', $q);
	$this->db->or_like('tgl_pembuatan', $q);
	$this->db->or_like('ket_bank', $q);
	$this->db->or_like('tgl_ins', $q);
	$this->db->or_like('tgl_updt', $q);
	$this->db->or_like('user_updt', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_bank', $q);
	$this->db->or_like('norek', $q);
	$this->db->or_like('nama_bank', $q);
	$this->db->or_like('atas_nama', $q);
	$this->db->or_like('cabang', $q);
	$this->db->or_like('tgl_pembuatan', $q);
	$this->db->or_like('ket_bank', $q);
	$this->db->or_like('tgl_ins', $q);
	$this->db->or_like('tgl_updt', $q);
	$this->db->or_like('user_updt', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_bank.php */
/* Location: ./application/models/M_bank.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-25 05:07:08 */
/* http://harviacode.com */