<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_jabatan extends CI_Model
{

    public $table = 'tb_jabatan';
    public $id = 'id_jabatan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_jabatan,kode_jabatan,nama_jabatan,ket_jabatan,tgl_insert,tgl_update,user');
        $this->datatables->from('tb_jabatan');
        //add this line for join
        //$this->datatables->join('table2', 'tb_jabatan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('c_jabatan/update/$1'),'Update')." | ".anchor(site_url('c_jabatan/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Yakin data akan dihapus ?\')"'), 'id_jabatan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_jabatan', $q);
	$this->db->or_like('kode_jabatan', $q);
	$this->db->or_like('nama_jabatan', $q);
	$this->db->or_like('ket_jabatan', $q);
	$this->db->or_like('tgl_insert', $q);
	$this->db->or_like('tgl_update', $q);
	$this->db->or_like('user', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_jabatan', $q);
	$this->db->or_like('kode_jabatan', $q);
	$this->db->or_like('nama_jabatan', $q);
	$this->db->or_like('ket_jabatan', $q);
	$this->db->or_like('tgl_insert', $q);
	$this->db->or_like('tgl_update', $q);
	$this->db->or_like('user', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_jabatan.php */
/* Location: ./application/models/M_jabatan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-06-29 12:46:48 */
/* http://harviacode.com */
