<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_karyawan extends CI_Model
{

    public $table = 'tb_karyawan';
    public $id = 'id_karyawan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_karyawan,id_jabatan,no_karyawan,nik_karyawan,nama_karyawan,pnd,tlp,email,avatar,avatar_url,alamat,ket_karyawan,tgl_ins,tgl_updt,user_updt');
        $this->datatables->from('tb_karyawan');
        //add this line for join
        //$this->datatables->join('table2', 'tb_karyawan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('c_karyawan/read/$1'),'Read')." | ".anchor(site_url('c_karyawan/update/$1'),'Update')." | ".anchor(site_url('c_karyawan/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_karyawan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_no_karyawan()
    {
      $query = $this->db->query("
          SELECT CONCAT('K',FRMTGL,COALESCE(ORD,'0001')) AS no_member
          FROM
          (
          SELECT CONCAT(Y,M) AS FRMTGL
           ,CASE
            WHEN ORD >= 10 THEN CONCAT('00',CAST(ORD AS CHAR))
            WHEN ORD >= 100 THEN CONCAT('0',CAST(ORD AS CHAR))
            WHEN ORD >= 1000 THEN CAST(ORD AS CHAR)
            ELSE CONCAT('000',CAST(ORD AS CHAR))
            END AS ORD
          FROM
          (
            SELECT
            CAST(MID(NOW(),3,2) AS CHAR) AS Y,
            CAST(MID(NOW(),6,2) AS CHAR) AS M,
            MID(NOW(),9,2) AS D,
            (MAX(CAST(RIGHT(no_karyawan,4) AS UNSIGNED)) + 1) AS ORD FROM tb_karyawan
          ) AS A
          ) AS AA
      ");

      if($query->num_rows() > 0)
      {
        return $query->row();
      } else {
        return false;
      }
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_karyawan', $q);
      	$this->db->or_like('id_jabatan', $q);
      	$this->db->or_like('no_karyawan', $q);
      	$this->db->or_like('nik_karyawan', $q);
      	$this->db->or_like('nama_karyawan', $q);
      	$this->db->or_like('pnd', $q);
      	$this->db->or_like('tlp', $q);
      	$this->db->or_like('email', $q);
      	$this->db->or_like('avatar', $q);
      	$this->db->or_like('avatar_url', $q);
      	$this->db->or_like('alamat', $q);
      	$this->db->or_like('ket_karyawan', $q);
      	$this->db->or_like('tgl_ins', $q);
      	$this->db->or_like('tgl_updt', $q);
      	$this->db->or_like('user_updt', $q);
      	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_karyawan', $q);
      	$this->db->or_like('id_jabatan', $q);
      	$this->db->or_like('no_karyawan', $q);
      	$this->db->or_like('nik_karyawan', $q);
      	$this->db->or_like('nama_karyawan', $q);
      	$this->db->or_like('pnd', $q);
      	$this->db->or_like('tlp', $q);
      	$this->db->or_like('email', $q);
      	$this->db->or_like('avatar', $q);
      	$this->db->or_like('avatar_url', $q);
      	$this->db->or_like('alamat', $q);
      	$this->db->or_like('ket_karyawan', $q);
      	$this->db->or_like('tgl_ins', $q);
      	$this->db->or_like('tgl_updt', $q);
      	$this->db->or_like('user_updt', $q);
      	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_karyawan.php */
/* Location: ./application/models/M_karyawan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-07-09 04:51:16 */
/* http://harviacode.com */
