<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_kelas extends CI_Model
{

    public $table = 'tb_kelas';
    public $id = 'id_kelas';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    function list_kelas()
    {
      $query = $this->db->query("
        SELECT id_kelas,nama_kelas
        FROM tb_kelas
        WHERE set_aktif = '1'
      ");

      if($query->num_rows() > 0)
      {
        return $query;
      } else {
        return false;
      }
    }

    // datatables
    function json() {
        $this->datatables->select('id_kelas,kode_kelas,nama_kelas,keterangan,tgl_ins,tgl_updt,user_updt');
        $this->datatables->from('tb_kelas');
        //add this line for join
        //$this->datatables->join('table2', 'tb_kelas.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('c_kelas/update/$1'),'Update')." | ".anchor(site_url('c_kelas/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Data akan dihapus ?\')"'), 'id_kelas');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function total_kelas()
    {
      $query = $this->db->query("
        SELECT COUNT(*) AS total_kelas
        FROM tb_kelas
      ");
      return $query->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kelas', $q);
	$this->db->or_like('kode_kelas', $q);
	$this->db->or_like('nama_kelas', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('tgl_ins', $q);
	$this->db->or_like('tgl_updt', $q);
	$this->db->or_like('user_updt', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kelas', $q);
	$this->db->or_like('kode_kelas', $q);
	$this->db->or_like('nama_kelas', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('tgl_ins', $q);
	$this->db->or_like('tgl_updt', $q);
	$this->db->or_like('user_updt', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_kelas.php */
/* Location: ./application/models/M_kelas.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-06-29 07:12:26 */
/* http://harviacode.com */
