<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_pengurang_bayaran extends CI_Model
{

    public $table = 'tb_pengurang_bayaran';
    public $id = 'id_pengurang';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_pengurang,kode_pengurang,jenis_pengurang,nama_pengurang,nominal,keterangan,tgl_ins,tgl_updt,user_updt');
        $this->datatables->from('tb_pengurang_bayaran');
        //add this line for join
        //$this->datatables->join('table2', 'tb_pengurang_bayaran.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('c_pengurang_bayaran/update/$1'),'Update')." | ".anchor(site_url('c_pengurang_bayaran/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_pengurang');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function total_pengurang_biaya($id_siswa,$kat_bayaran)
    {
      $query = $this->db->query("
          SELECT SUM(nominal) nominal -- A.id_pengurang,nama_pengurang,
          FROM tb_bayaran_pengurang A
          LEFT JOIN tb_siswa C
          ON A.id_siswa = C.id_siswa
          LEFT JOIN tb_pengurang_bayaran B
          ON A.id_pengurang = B.id_pengurang
          WHERE A.id_siswa = '".$id_siswa."' AND id_kat_bayaran = '".$kat_bayaran."'
      ");

      if($query->num_rows() > 0)
      {
        return $query->row();
      } else {
        return 0;
      }

    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pengurang', $q);
      	$this->db->or_like('kode_pengurang', $q);
      	$this->db->or_like('nama_pengurang', $q);
      	$this->db->or_like('nominal', $q);
      	$this->db->or_like('keterangan', $q);
      	$this->db->or_like('tgl_ins', $q);
      	$this->db->or_like('tgl_updt', $q);
      	$this->db->or_like('user_updt', $q);
      	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pengurang', $q);
	$this->db->or_like('kode_pengurang', $q);
	$this->db->or_like('nama_pengurang', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('tgl_ins', $q);
	$this->db->or_like('tgl_updt', $q);
	$this->db->or_like('user_updt', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_pengurang_bayaran.php */
/* Location: ./application/models/M_pengurang_bayaran.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-07-09 05:58:17 */
/* http://harviacode.com */
