<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_uang_masuk extends CI_Model
{

    public $table = 'tb_uang_masuk';
    public $id = 'id_uang_masuk';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_uang_masuk,id_kat_uang_masuk,no_bukti,nama_uang_masuk,terima_dari,diterima_oleh,untuk,nominal,ket_uang_masuk,tgl_uang_masuk,tgl_ins,tgl_updt,user_updt');
        $this->datatables->from('tb_uang_masuk');
        //add this line for join
        //$this->datatables->join('table2', 'tb_uang_masuk.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('c_uang_masuk/update/$1'),'Update')." | ".anchor(site_url('c_uang_masuk/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_uang_masuk');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_uang_masuk', $q);
	$this->db->or_like('id_kat_uang_masuk', $q);
	$this->db->or_like('no_bukti', $q);
	$this->db->or_like('nama_uang_masuk', $q);
	$this->db->or_like('terima_dari', $q);
	$this->db->or_like('diterima_oleh', $q);
	$this->db->or_like('untuk', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('ket_uang_masuk', $q);
	$this->db->or_like('tgl_uang_masuk', $q);
	$this->db->or_like('tgl_ins', $q);
	$this->db->or_like('tgl_updt', $q);
	$this->db->or_like('user_updt', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_uang_masuk', $q);
	$this->db->or_like('id_kat_uang_masuk', $q);
	$this->db->or_like('no_bukti', $q);
	$this->db->or_like('nama_uang_masuk', $q);
	$this->db->or_like('terima_dari', $q);
	$this->db->or_like('diterima_oleh', $q);
	$this->db->or_like('untuk', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('ket_uang_masuk', $q);
	$this->db->or_like('tgl_uang_masuk', $q);
	$this->db->or_like('tgl_ins', $q);
	$this->db->or_like('tgl_updt', $q);
	$this->db->or_like('user_updt', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_uang_masuk.php */
/* Location: ./application/models/M_uang_masuk.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-21 04:56:31 */
/* http://harviacode.com */
